LakeWayCottages/LakeWayCottages/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,include
from basic_app.views import index
from django.contrib.auth.views import PasswordChangeView,PasswordResetDoneView,PasswordResetView,PasswordResetConfirmView,PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('app/',include('basic_app.urls')),
    path('reset_password',PasswordResetView.as_view(template_name='password_resetting/password_reset_form.html'),name='reset_password'),
    path('password_reset_done',PasswordResetDoneView.as_view(template_name='password_resetting/password_reset_done.html'),name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(template_name='password_resetting/password_reset_confirm.html'),name='password_reset_confirm'),
    path('reset/done/',PasswordResetCompleteView.as_view(template_name='password_resetting/password_reset_complete.html'),name='password_reset_complete')
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

LakeWayCottages/basic_app/urls.py
from django.urls import path
from basic_app import views
app_name='basic_app'
urlpatterns = [
    path('',views.index,name='index'),
    path('createFeature/',views.createFeature.as_view(),name='createFeature'),
    path('updateFeature/<int:pk>/',views.updateFeature.as_view(),name='updateFeature'),
    path('deleteFeature/<int:pk>/', views.deleteFeature.as_view(), name='deleteFeature'),
    path('createApartment/',views.createApartment.as_view(),name='createApartment'),
    path('updateApartment/<int:pk>/',views.updateApartment.as_view(),name='updateApartment'),
    path('deleteApartment/<int:pk>/', views.deleteApartment.as_view(), name='deleteApartment'),
    path('email/',views.contactMail,name='mail'),
    path('login/',views.userLogin,name='login'),
    path('logout/',views.user_logout,name='logout')
]

LakeWayCottages/basic_app/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class features(models.Model):
    image=models.ImageField(upload_to='images',blank=True)
    desc=models.TextField(max_length=250)

    def get_absolute_url(self):
        return reverse("index")


class apartmentType(models.Model):
    ApartmentTitle=models.CharField(max_length=15)
    image=models.ImageField(upload_to='images',blank=True)
    desc=models.TextField(max_length=256)

    def get_absolute_url(self):
        return reverse("index")

LakeWayCottages/basic_app/views.py
from django.conf import settings
from django.core.checks import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView, ListView
from basic_app import models
from django.core.mail import send_mail
from django.contrib.auth import authenticate, login,logout


# Create your views here.

def index(request):
    feature = models.features.objects.all()
    apartment = models.apartmentType.objects.all()
    return render(request, 'basic_app/index2.html', {'obj': feature, 'apartment': apartment})


class createFeature(CreateView):
    fields = ('image', 'desc')
    model = models.features


class updateFeature(UpdateView):
    fields = ('image', 'desc')
    model = models.features


class deleteFeature(DeleteView):
    context_object_name = 'feature'
    model = models.features
    success_url = reverse_lazy("basic_app:index")


class createApartment(CreateView):
    fields = ('image','ApartmentTitle', 'desc')
    model = models.apartmentType


class updateApartment(UpdateView):
    fields = ('image', 'desc')
    model = models.apartmentType


class deleteApartment(DeleteView):
    context_object_name = 'apartment'
    model = models.apartmentType
    success_url = reverse_lazy("basic_app:index")


def contactMail(request):
    check = False
    if request.method == 'POST':
        username = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        print(username)
        print(email)
        print(message)
        msg = "Name : " + username + "\n" + "Email : " + email + "\n" + "Message : " + message
        send_mail(
            subject,
            msg,
            settings.EMAIL_HOST_USER,
            ['mwajihrehman@gmail.com'],
            fail_silently=False,
        )


def userLogin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user:
            login(request, user)
            return HttpResponseRedirect(reverse('index'))
        else:
            return HttpResponse("Wroong details")

    else:
        return render(request, 'basic_app/login.html')


def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('basic_app:index'))

LakeWayCottages/templates/basic_app/index.html
{%extends 'basic_app/base.html'%}
{%block body_block%}
{%load static%}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{%static "hero1.jpg"%}" height="700px" alt="First slide">
      <div class="carousel-caption">
        <h1 class="text-uppercase text-white font-weight-bold">In the Heart of Naran Valley</h1>
        <h3>Enjoy the epic view of Nature</h3>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{%static "hero3.jpeg"%}" height="700px" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{%static "hero2.jpg"%}" height="700px" alt="Third slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{%static "hero4.jpeg"%}" height="700px" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>



<section id="about" class="about ">
      <div class="jumbotron container " style="background: linear-gradient(90deg, rgba(255,255,255,1) 0%, rgba(118,146,43,1) 100%, rgba(255,255,255,1) 100%)" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-6 video-box align-self-baseline" data-aos="zoom-in" data-aos-delay="100">
            <img src="">
          </div>

          <div class="col-lg-6 pt-3 pt-lg-0 content">
            <h3>Something about LakeWay Cottages.</h3>
            <h4 class="font-italic">
              5G Group of Companies presents  Lakeway Cottages which is being constructed on 20.5 Kanal Land towards the Saif ul Mulook Lake in Naran, Pakistan.

            </h4>
            <ul>
              <li><i class="bx bx-check-double"></i>Located in a Main Naran valley of outstanding natural beauty.</li>
              <li><i class="bx bx-check-double"></i> Naran is the number one and top crowd catch traveling and touring HUB of Pakistan. Which is located in KPK East end and attracted the Punjab and Sindh public alongwith foreigners as well.</li>
              <li><i class="bx bx-check-double"></i>All the cottages have have river walks abounding in Mountain Valley. Just 10 minutes walk from Naran Bazar at Jheel Road.</li>
              <li><i class="bx bx-check-double"></i>All the cottages have have river walks abounding in Mountain Valley. Just 10 minutes walk from Naran Bazar at Jheel Road.</li>
            </ul>

          </div>

        </div>

      </div>
</section>
    <!-- ======= Services Section ======= -->
    <section id="services" class="services section-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Benifits</h2>
          <p>What Should you Invest in us?</p>
        </div>

        <div class="row" data-aos="fade-up" data-aos-delay="200">
          <div class="col-md-6">
            <div class="icon-box">

              <h2><a href="#" id="flash"><i class="icofont-computer"></i>Best investment for rental income</a></h2>
            </div>
          </div>

          <div class="col-md-6 mt-4 mt-md-0">
            <div class="icon-box">
              <i class="icofont-image"></i>
              <h2><a href="#" id="flash">Asset in tourism sector</a></h2>
            </div>
          </div>
          <div class="col-md-6 mt-4 mt-md-0">
            <div class="icon-box">
              <i class="icofont-settings"></i>
              <h2><a href="#" id="flash">Future best investment</a></h2>
            </div>
          </div>
          <div class="col-md-6 mt-4 mt-md-0">
            <div class="icon-box">
              <i class="icofont-earth"></i>
              <h2><a href="#" id="flash">long lasting asset</a></h2>
            </div>
          </div>
          <div class="col-md-6 mt-4 mt-md-0">
            <div class="icon-box">
              <i class="icofont-tasks-alt"></i>
              <h2><a href="#" id="flash">Asset & investment</a></h2>
            </div>
          </div>
        </div>

      </div>
    </section>


    <section id="portfolio" class="parallax portfolio" style="background-image: url({% static 'wood.jpg' %});">
      <div class="container " data-aos="fade-up">

        <div class="section-title">
          <h2 class="text-white">Features</h2>
          <p class="text-white">Check out our Features</p>
        </div>


        <div class="row portfolio-container " data-aos="fade-up" data-aos-delay="200">
    {%for f in obj%}
          <div class="col-xl-2 col-md-6 portfolio-item filter-app d-flex justify-content-center">
            <img src="/media/{{f.image}}" style="height=350px;width:350px" class="img-fluid" alt="">
            <div class="portfolio-info bg-success" >
              <h4 >{{f.desc}}</h4>
            </div>

          </div>

  {%endfor%}

        </div>
        {%if request.user.is_authenticated%}
          {%for f in obj%}
<div class="d-flex justify-content-around">
              <h4 class="text-white">{{f.desc}}</h4>
            <div class="container d-flex flex-row d-flex justify-content-center">
              <p><a class="btn btn-warning" href="{%url 'basic_app:updateFeature' pk=f.id%}">Edit Feature</a></p>
              <p><a class="btn btn-danger" href ="{%url 'basic_app:deleteFeature' pk=f.id%}">Delete Feature</a></p>
              </div>
  </div>
  {%endfor%}
        {%endif%}

      </div>
    </section>



  <section id="team" class="team section-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Apartments</h2>
          <p>Check out our Apartment type and Division</p>
        </div>

        <div class="row d-flex justify-content-center">
        {%for a in apartment%}
          <div class="col-lg-4 col-md-6 ">
            <div class="member " data-aos="fade-up" data-aos-delay="100 ">
              <div class="pic"><img src="/media/{{a.image}}" height="350px" width="350px" class="img-fluid" alt=""></div>
              <div class="member-info" style=" background: linear-gradient(to top left, #ffffff 0%, #76922b 100%);">
                <h4>{{a.ApartmentTitle}}</h4>
                <span>{{a.desc}}</span>

              </div>
            </div>
            <div class="container d-flex flex-row ">
              <p><a class="btn btn-warning" href="{%url 'basic_app:updateApartment' pk=a.id%}">Edit Apartment</a></p>
              <p><a class="btn btn-danger" href ="{%url 'basic_app:deleteApartment' pk=a.id%}">Delete Apartment</a></p>
              </div>

          </div>

         {%endfor%}

        </div>

      </div>
    </section>
   <section id="contact" class="contact">
      <div class="container" data-aos="fade-up"">

    <div class=" section-title">
        <h2>Contact</h2>
        <p>Contact Us</p>
      </div>

      <div class="row">

        <div class="col-lg-6">

          <div class="row">
            <div class="col-md-12">
              <div class="info-box">
                <a href="https://www.google.com/maps/place/5G+Properties/@33.6700425,72.9971868,17z/data=!3m1!4b1!4m5!3m4!1s0x38df95f8b4b2f895:0xf88a1971f9e9fde5!8m2!3d33.6700381!4d72.9993755">
                <i class="bx bx-map" style="color:#76922b"></i>
                  </a>
                <h3>Our Address</h3>
                <p>Office No. 31, 2nd Floor, Al Hameed Plaza, G-11 Markaz, Islamabad</p>
              </div>
            </div>
            <div class="col-md-6">
              <div class="info-box mt-4">
                <a class="btn-floating btn-gplus mx-1" href="mailto:hasanfmradio@gmail.com">
                <i class="bx bx-envelope" style="color:#76922b"></i>
                </a>
                <h3>Email Us</h3>
              </div>
            </div>
            <div class="col-md-6">
              <div class="info-box mt-4">
                <a class="btn-floating btn-gplus mx-1" href="tel:+923337777703">
                <i class="bx bx-phone-call" style="color:#76922b"></i>
                </a>
                <h3>Call Us</h3>
              </div>
            </div>
          </div>

        </div>

        <div class="col-lg-6 mt-4 mt-lg-0">
          <form  action="{%url 'basic_app:mail'%}"  method="POST"  class="php-email-form">
            <div class="form-row">
              <div class="col-md-5 form-group">
                <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                <div class="validate"></div>
              </div>
              <div class="col-md-5 form-group">
                <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                <div class="validate"></div>
              </div>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
              <div class="validate"></div>
            </div>
            <div class="form-group">
              <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
              <div class="validate"></div>
            </div>
          <div class="mb-3">
               <div class="loading">Your message has been sent. Thank you!</div>
              <div class="error-message"></div>

            </div>
            <div class="text-center"><a href="{%url 'basic_app:index'%}"><button id="btn" type="submit" style="background-color:#76922b">Send Message</button></a></div>
            {%csrf_token%}

          </form>

        </div>

      </div>

      </div>
    </section>




</script>
{%endblock%}

LakeWayCottages/templates/basic_app/index2.html
{%extends 'basic_app/base.html'%}
{%block body_block%}

{%load static%}

  <!-- ======= Hero Section ======= -->
  <section id="hero">
    <div class="hero-container">
      <div id="heroCarousel" class="carousel slide carousel-fade" data-ride="carousel">

        <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

        <div class="carousel-inner" role="listbox">

          <!-- Slide 1 -->
          <div class="carousel-item active">
      <div class="carousel-background"><img class="d-block w-100" src="{%static "hero3.jpeg"%}" height="700px" alt="Third slide"></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animated fadeInDown"><span>LakeWay</span> Cottages</h2>
                <p class="animated fadeInUp">Where Convenience Meets Luxury.</p>
                <div>
                  <a href="#menu" class="btn-menu animated fadeInUp scrollto">About Project</a>
                  <a href="#book-a-table" class="btn-book animated fadeInUp scrollto">Contact us<a>
                </div>
              </div>
            </div>
          </div>

          <!-- Slide 2 -->
          <div class="carousel-item" >
            <div class="carousel-background"><img class="d-block w-100" src="{%static "hero1.jpg"%}" height="700px" alt="Third slide"></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animated fadeInDown">Where Excellence and Convenience Meet.</h2>
                <p class="animated fadeInUp">State of the Art designed cottages</p>
                <div>
                  <a href="#menu" class="btn-menu animated fadeInUp scrollto">About Project</a>
                  <a href="#book-a-table" class="btn-book animated fadeInUp scrollto">Contact Us</a>
                </div>
              </div>
            </div>
          </div>

          <!-- Slide 3 -->
          <div class="carousel-item">
            <div class="carousel-background"><img class="d-block w-100" src="{%static "hero4.jpeg"%}" height="700px" alt="Third slide"></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animated fadeInDown">Location, Community, Quality Living. It Starts Here!</h2>
                <p class="animated fadeInUp">In the heart of Naran Valley</p>
                <div>
                  <a href="#menu" class="btn-menu animated fadeInUp scrollto">About Project</a>
                  <a href="#book-a-table" class="btn-book animated fadeInUp scrollto">Contact Us</a>
                </div>
              </div>
            </div>
          </div>

                      <div class="carousel-item">
            <div class="carousel-background"><img class="d-block w-100" src="{%static "hero2.jpg"%}" height="700px" alt="Third slide"></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animated fadeInDown">Unparalleled Views. Exceptional Style. Nonstop Luxury.</h2>
                <div>
                  <a href="#menu" class="btn-menu animated fadeInUp scrollto">About Project</a>
                  <a href="#book-a-table" class="btn-book animated fadeInUp scrollto">Contact Us</a>
                </div>
              </div>
            </div>
          </div>



        </div>

        <a class="carousel-control-prev" href="#heroCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon icofont-simple-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>

        <a class="carousel-control-next" href="#heroCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon icofont-simple-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>

      </div>
    </div>
  </section><!-- End Hero -->

  <main id="main">


    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container" >

        <div class="row d-flex justify-content-center">

          <div class="col-lg-6 video-box align-self-baseline" data-aos="zoom-in" data-aos-delay="100">
            <img class="img-fluid" src="{%static 'd26e2cb2-5e08-48c8-b06b-bac45aa8aab8.jpg'%}">
          </div>

          <div class="col-lg-6 pt-3 pt-lg-0 content">

              <h3>Something About<strong> the location,beauty and idea of our innovative Cottages</strong></h3>
              <p>
                    5G Group of Companies presents  Lakeway Cottages which is being
                  constructed on 20.5 Kanal Land towards the Saif ul Mulook Lake in Naran, Pakistan.              </p>
              <p class="font-italic">


              </p>
              <ul>
                <li><i class="bx bx-check-double"></i> Located in a Main Naran valley of outstanding natural beauty.</li>
                <li><i class="bx bx-check-double"></i>  Naran is the number one and top crowd catch traveling and touring HUB of Pakistan. Which is located in KPK East end and attracted the Punjab and Sindh public alongwith foreigners as well.</li>
                <li><i class="bx bx-check-double"></i>All the cottages have have river walks abounding in Mountain Valley. Just 10 minutes walk from Naran Bazar at Jheel Road.</li>

              </ul>
              <p>
                The making of such a state of the art project is work of world-class award-winning teams of architects,
                  designers, project consultants, marketing and sales teams, and experienced staff. We offer our gratitude
                  to everyone involved in helping us to construct a design- Lakeview Cottages into reality.

              </p>


          </div>

        </div>

      </div>
    </section><!-- End About Section -->

    <!-- ======= Whu Us Section ======= -->
    <section id="why-us" class="why-us">
      <div class="container">

        <div class="section-title">
          <h2>Why choose to invest in<span> LakeWay Cottages</span></h2>
          <p>“THE BEST INVESTMENT ON EARTH IS EARTH”<br>
                INVEST & LIVE IN NATURE</p>
        </div>

        <div class="row">

          <div class="col-lg-4">
            <div class="box">
              <span>01</span>
              <h4>Commercial Attraction</h4>
              <p>After completion of Motorway and CPEC, Naran is the main commercial and tourist destination of northern areas and Pakistan.</p>
            </div>
          </div>

          <div class="col-lg-4 mt-4 mt-lg-0">
            <div class="box">
              <span>02</span>
              <h4>Tourist Attraction</h4>
              <p>As per statistics more than 10 million people visited Naran and northern areas during 2018 and 2019.  Naran will be the main tourist attraction for Locals as well as for foreigners in coming years.</p>
            </div>
          </div>

          <div class="col-lg-4 mt-4 mt-lg-0">
            <div class="box">
              <span>03</span>
              <h4> Invest in us because....</h4>
              <p>Annual Returns 10% (Guaranteed by 5G Group of Companies)
 Straight 10 days free stay for owners
</p>
            </div>
          </div>

        </div>

      </div>
    </section><!-- End Whu Us Section -->




    <!-- ======= Events Section ======= -->
       <div class="section-title">
          <h2>Check out <span>State of the art</span> features in our Cottages</h2>
        </div>
    <section id="events" class="events d-flex justify-content-center" >
         <div id="carouselExampleSlidesOnly" class=" carousel slide " data-ride="carousel" style="height:30%;width:30%">

  <div class="carousel-inner ">
    {%for f in obj|slice:":"%}
    {%if forloop.first%}
    <div class="carousel-item active ">
      <!-- continue -->
    </div>
    {%else%}
    <div class="carousel-item   ">
      <img class="d-block w-100 img-fluid " src="/media/{{f.image}}" height="230px" width="200px" alt="Second slide">
      <h2 class="text-white ">{{f.desc}}</h2>
    </div>
   {%endif%}

    {%endfor%}

  </div>
</div>

    </section><!-- End Events Section -->

 <!-- ======= Chefs Section ======= -->
    <section id="chefs" class="chefs">
      <div class="container">

        <div class="section-title">
          <h2>Our Appartment <span>type and division</span></h2>
          <p>Lakeway cottages offers one & two rooms fully furnished luxury cottages*.  These cottages have spacious bedrooms, attached bath and small functional kitchen.  We offer three different types and sizes of cottages for our clients.</p>
        </div>

        <div class="row">
    {%for a in apartment%}
          <div class="col-lg-4 col-md-6">
            <div class="member">
              <div class="pic"><img src="/media/{{a.image}}" class="img-fluid" alt=""></div>
              <div class="member-info">
                <h4>{{a.ApartmentTitle}}}</h4>
                <span>{{a.desc}}</span>
                <div class="social">
                  <a href=""><i class="icofont-twitter"></i></a>
                  <a href=""><i class="icofont-facebook"></i></a>
                  <a href=""><i class="icofont-instagram"></i></a>
                  <a href=""><i class="icofont-linkedin"></i></a>
                </div>
              </div>
            </div>
          </div>
          {%endfor%}
        </div>

      </div>
    </section><!-- End Chefs Section -->







    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      <div class="container">

        <div class="section-title">
          <h2><span>Contact</span> Us</h2>
        </div>
      </div>

      <div class="map">
        <iframe style="border:0; width: 100%; height: 350px;"  src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3320.502978447334!2d72.99718681520504!3d33.67003808071161!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38df95f8b4b2f895%3A0xf88a1971f9e9fde5!2s5G%20Properties!5e0!3m2!1sen!2s!4v1589510980700!5m2!1sen!2s" frameborder="0" allowfullscreen></iframe>
      </div>

      <div class="container mt-5">

        <div class="info-wrap">
          <div class="row">
            <div class="col-lg-3 col-md-6 info">
              <i class="icofont-google-map"></i>
              <h4>Location:</h4>
              <p>Office No. 31, 2nd Floor, Al Hameed Plaza<br>,G-11 Markaz, Islamabad </p>
            </div>

            <div class="col-lg-3 col-md-6 info mt-4 mt-lg-0">
              <i class="icofont-clock-time icofont-rotate-90"></i>
              <h4>Open Hours:</h4>
              <p>Monday-Saturday:<br>11:00 AM - 2300 PM</p>
            </div>

            <div class="col-lg-3 col-md-6 info mt-4 mt-lg-0">
            <a class="btn-floating btn-gplus mx-1" href="mailto:hasanfmradio@gmail.com">
              <i class="icofont-envelope"></i>
            </a>
              <h4>Email:</h4>
              <p>hasanfmradio@gmail.com</p>
            </div>

            <div class="col-lg-3 col-md-6 info mt-4 mt-lg-0">
            <a class="btn-floating btn-gplus mx-1" href="tel:+923337777703">
              <i class="icofont-phone"></i>
            </a>
              <h4>Call:</h4>
              <p>+92333 777 7703</p>
            </div>
          </div>
        </div>

        <form  action="{%url 'basic_app:mail'%}"  method="POST"  class="php-email-form">
          <div class="form-row">
            <div class="col-md-6 form-group">
              <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
              <div class="validate"></div>
            </div>
            <div class="col-md-6 form-group">
              <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
              <div class="validate"></div>
            </div>
          </div>
          <div class="form-group">
            <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
            <div class="validate"></div>
          </div>
          <div class="form-group">
            <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
            <div class="validate"></div>
          </div>
          <div class="mb-3">
               <div class="loading">Your message has been sent. Thank you!</div>
              <div class="error-message"></div>

            </div>
   <div class="text-center"><a href="{%url 'basic_app:index'%}"><button id="btn" type="submit" style="background-color:#76922b">Send Message</button></a></div>
            {%csrf_token%}        </form>

      </div>
    </section><!-- End Contact Section -->

  </main>
{%endblock%}

LakeWayCottages/templates/password_resetting/password_reset_complete.html
{% extends 'basic_app/base.html'%}
{%block body_block%}
<body style="background:#76922b">
<br>
<br>
<br>
<br>
<br>
<br>
    <div class="alert alert-info" role="alert">
        <p class="d-flex justify-content-center">Congratulations your password has been succesfully changed</p>
    </div>
        <a class="d-flex justify-content-center btn btn-primary" href="{%url 'basic_app:login'%}" >Sign in!</a>


<br>
</body>
{%endblock%}

LakeWayCottages/templates/password_resetting/password_reset_confirm.html
{% extends 'basic_app/base.html'%}
{%block body_block%}
<body style="background:#76922b">
<br>
<br>
<br>
<br>
<br>
<br>
<div class="jumbotron">
    <form method="POST">

{{form}}
        <div class="container">
  <div class="row">
    <div class="col text-center">
      <input type="submit"   class="btn btn-primary" value="Reset Password">
    </div>
  </div>
</div>
        {%csrf_token%}
</form>
</div>
<br>
</body>
{%endblock%}